config/routes.rb
Rails.application.routes.draw do

  resource :contact_forms
  

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get '/contacts', to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  get 'homes/show'
  get 'posts/local_news', to: "posts#local_news"
  get 'posts/sports', to: "posts#sports"
  get 'posts/database', to: "posts#database"
  devise_for :users
  resources :posts
  resources :homes, only: [:show]

  get "pages/contact" => "pages#contact"
  get "pages/about" => "pages#about"
  get "pages/election2016" => "pages#election2016"

  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attributes :name,  :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message

  def headers
    {
      :to => "seaboltmarketing@gmail.com",
      :subject => "User created an account"
    }
  end
end

app/models/message.rb
class Message 
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

	attr_accessor :name, :email, :subject, :content
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	def shold_generate_new_friendly_id?
  		title_changed?
  	end
	
	def day_published
  		"Published #{created_at.strftime('%-b %-d, %Y')}"
  	end 

  	scope :most_recent, -> {order(id: :desc)}

  	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
   def new
      @contact_form = ContactForm.new
    end

    def create
      begin
        @contact_form = ContactForm.new(params[:contact_form])
        @contact_form.request = request
        if @contact_form.deliver
          flash.now[:notice] = 'Thank you for your message!'
        else
          render :new
        end
      rescue ScriptError
        flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end

	def election_2016

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create, :database]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  def local_news
    @posts = Post.most_recent
  end 

  def sports
    @posts = Post.most_recent
  end 

  def database
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.most_recent
    @sidebar = Post.where(ranking: "local").limit(2)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :description, :photo, :ranking, :photo_file_name, :caption)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact_forms/create.html.erb
<div class="col-xs-5 col-xs-push-3">
<h2>Thank You</h2>
<p>Someone from our office will be in contact with you soon.</p>
</div>

app/views/contact_forms/new.html.erb
<% provide(:page_title, "Contact") %>

<div class="row">
	<div class="col-md-8 col-md-push-2 col-sm-12">
		<h3>Contact Us</h3>
		<br />
		<%= simple_form_for @contact_form do |f| %>
		    <%= f.input :name, :required => false %>
		    <%= f.input :email, :required => false %>
		    <%= f.input :message, :required => false %>
		    <br />
		    <%= f.button :submit, 'Send message', class: "btn btn-custom" %>
		 <% end %> 
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class='navbar-brand' href='/'>
      <span style="color: #7c98f5">Bay</span><span class='light'>Today</span>
    </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <a href="/posts" class="nav_link">Home <span class="sr-only">(current)</span></a></li>
        <li> <%= link_to "Sports", posts_sports_path, class: 'nav_link' %></li>
        <li><%= link_to "Local", posts_local_news_path, class: 'nav_link' %></li>
        <li><%= link_to "About", pages_about_path, class: 'nav_link' %></li>
      </ul>
       <a href="http://www.pinterest.com/"><div class="pull-right social_container" id="pinterest">
         <i class="fa fa-pinterest-p social_icons" id="social_pinterest" style="font-size: 19px;"></i>
      </div></a>
       <a href="http://www.google.com/"><div class="pull-right social_container" id="google">
        <i class="fa fa-google-plus" id="social_google" style="font-size: 18px;"></i>
      </div></a>
      <a href="http://www.twitter.com/"><div class="pull-right social_container" id="twitter">
        <i class="fa fa-twitter social_icons" id="social_twitter" style="font-size: 20px;"></i>
      </div></a>
      <a href="http://www.facebook.com/"><div class="pull-right social_container" id="facebook">
        <i class="fa fa-facebook-f social_icons" id="social_facebook" style="font-size: 19px;"></i>
      </div></a>


      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <head>
  <title><%= yield(:page_title) %> | BayToday</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <script type="text/javascript" src="http://code.jquery.com/color/jquery.color-2.1.2.js"></script>

  </head>

  <body>
  	<%= render 'layouts/nav' %>
    <br>
  	<div class="container">
    	<%= yield %>
    </div>
    <div class="footer">
    <p class="link">
      <a href="/posts" class="nav_link">Home</a> | <%= link_to "About", pages_about_path, class: 'nav_link' %> | <%= link_to "Contact", new_contact_forms_path, class: 'nav_link' %> | 
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav_link' %> | 
        <%= link_to "New Post", new_post_path, class: 'nav_link' %> | <%= link_to "Database", posts_database_path, class: 'nav_link' %>
      <% else %> 
        <%= link_to "Admin", new_user_session_path, class: 'nav_link' %>
      <% end %>




      <p class="copyright">&copy; 2016 by BayToday. All right reserved.</p>
      </p> 
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:page_title, "About") %>

<div class="row">
	<div class="col-xs-10 col-xs-push-1">
		<h1 class="section_header">About</h1>
		<hr class="break">
		<p>VHS sustainable glossier, vice narwhal actually subwaytile poke fashion axe. Bicycle rights disrupt mlkshk vegan woke pop-up, gastropub kombucha chartreuse. Lyft marfa man bun, freegan keytar chia poke poutine. Actually enamel pin pug tote bag. Twee gastropub af, jean shorts jianbing celiac shabby chic. Kinfolk yuccie hella copper mug man braid retro. Wolf chillwave swag marfa PBR&B gochujang kogi, listicle leggings lumbersexual hoodie.
		<br /><br />
		La croix swag vegan freegan, flexitarian kogi raw denim brunch. Locavore mumblecore tattooed jianbing, fingerstache flexitarian iPhone seitan letterpress vegan try-hard messenger bag. Tumblr snackwave small batch four loko brunch kitsch chia. Lyft pok pok subway tile polaroid, cardigan kale chips tumeric heirloom sartorial prism. Migas irony letterpress, you probably haven't heard of them activated charcoal crucifix tofu retro austin marfa food truck bespoke polaroid yuccie. Skateboard bicycle rights kinfolk, fingerstache brunch fixie quinoa tousled tofu +1 try-hard copper mug biodiesel bitters. Fanny pack sartorial microdosing ennui, single-origin coffee wayfarers jianbing edison bulb franzen cred fixie.</p> 
		<br><br>
		<h3 class="section_sub_header">Meet Our Team</h3>
		<hr class="break">
		<br>
	</div>
	<div class="col-xs-10 col-xs-push-1">
		<div class="col-md-4 col-xs-12 text-center">
			<%= image_tag('profile4.jpg', class: "profile_picture") %>
		</div>
		<div class="col-md-8 col-xs-12">
			<h3 class="section_sub_header">Jane Smith</h3><h5 class="section_subheader">Editor-in-Chief</h5>
			<p>Stumptown subway tile vaporware coloring book lyft. Kitsch VHS pickled, williamsburg freegan la croix glossier cornhole neutra cardigan. Pour-over fam man bun seitan you probably haven't heard of them small batch. Raclette migas put a bird on it man bun flannel, whatever affogato lomo. Try-hard cardigan vexillologist sartorial. Stumptown keffiyeh copper mug, blue bottle cornhole bicycle rights drinking vinegar biodiesel photo booth. Vape selvage small batch, bicycle rights venmo mumblecore actually bitters enamel pin swag paleo marfa poke.
			</p> 
			<br><br> 
		</div>
	</div>
	<div class="col-xs-10 col-xs-push-1">
		<div class="col-md-4 col-md-push-8 col-xs-12 text-center">
			<%= image_tag('profile1.jpg', class: "profile_picture") %>
		</div>
		<div class="col-md-8 col-md-pull-4 col-xs-12 profile_content_right">
			<h3 class="section_sub_header">Dennis Anderson</h3><h5 class="section_subheader">President</h5>
			<p>Stumptown subway tile vaporware coloring book lyft. Kitsch VHS pickled, williamsburg freegan la croix glossier cornhole neutra cardigan. Pour-over fam man bun seitan you probably haven't heard of them small batch. Raclette migas put a bird on it man bun flannel, whatever affogato lomo. Try-hard cardigan vexillologist sartorial. Stumptown keffiyeh copper mug, blue bottle cornhole bicycle rights drinking vinegar biodiesel photo booth. Vape selvage small batch, bicycle rights venmo mumblecore actually bitters enamel pin swag paleo marfa poke.
			</p> 
			<br><br>
		</div>
	</div>
	<div class="col-xs-10 col-xs-push-1">
		<div class="col-md-4 col-xs-12 text-center">
			<%= image_tag('profile2.jpg', class: 'profile_picture') %>
		</div>
		<div class="col-md-8 col-xs-12">
			<h3 class="section_sub_header">Sarah Jones</h3><h5 class="section_subheader">Director of Operations</h5>
			<p>Stumptown subway tile vaporware coloring book lyft. Kitsch VHS pickled, williamsburg freegan la croix glossier cornhole neutra cardigan. Pour-over fam man bun seitan you probably haven't heard of them small batch. Raclette migas put a bird on it man bun flannel, whatever affogato lomo. Try-hard cardigan vexillologist sartorial. Stumptown keffiyeh copper mug, blue bottle cornhole bicycle rights drinking vinegar biodiesel photo booth. Vape selvage small batch, bicycle rights venmo mumblecore actually bitters enamel pin swag paleo marfa poke.
			</p> 
			<br><br> 
		</div>
	</div>
	<div class="col-xs-10 col-xs-push-1">	
		<div class="col-md-4 col-md-push-8 col-xs-12 text-center">
			<%= image_tag('profile3.jpg', class: "profile_picture") %>
		</div>
		<div class="col-md-8 col-md-pull-4 col-xs-12 profile_content_right">
			<h3 class="section_sub_header">Edward Rodriguez</h3><h5 class="section_subheader">Editorial Director, Digital</h5>
			<p>Stumptown subway tile vaporware coloring book lyft. Kitsch VHS pickled, williamsburg freegan la croix glossier cornhole neutra cardigan. Pour-over fam man bun seitan you probably haven't heard of them small batch. Raclette migas put a bird on it man bun flannel, whatever affogato lomo. Try-hard cardigan vexillologist sartorial. Stumptown keffiyeh copper mug, blue bottle cornhole bicycle rights drinking vinegar biodiesel photo booth. Vape selvage small batch, bicycle rights venmo mumblecore actually bitters enamel pin swag paleo marfa poke.
			</p> 
			<br><br>
		</div>
	</div>
	<div class="col-xs-12">
	<br /><br /><br />
	</div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => {:multipart => true} do |f| %>
  
  <%= f.error_notification %>
  <div class="field">
      <%= f.input :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.input :content, class: 'form-control', :as => :text %>
  </div>
  <div class="field">
    <%= f.input :description, class: 'form-control', :as => :text %>
  </div>
  <div class="field">
    <%= f.input :ranking, collection: ['today','headline','local','headline local', 'sports', 'headline sports', 'record'] %>
  </div>
  <div class="actions">
    <%= f.label :photo %> 
    <%= f.file_field :photo, class: "white"  %>
  </div> 
   <div class="field">
    <%= f.input :caption, class: 'form-control' %>
  </div>
  <br />
  <div class="actions">
    <%= f.button :submit, :class => 'btn btn-custom' %>
  </div> 
<% end %>

app/views/posts/database.html.erb
<% provide(:page_title, "Database") %>

<div class="row">
	<div class="col-xs-10 col-xs-push-1">
		<h1 class="section_header">Database</h1>
		<hr class="break">
		<br />
		<div class="white_background">
			<table class="table table-hover table-striped">
				<thead>
				<tr>
					<th>Title</th>
					<th>Status</th>
					<th>Access</th>
				</tr>
				</thead>
				<tbody>
				<% @posts.each do |post| %>
				<tr class='clickable-row' data-href='<%= post.slug %>/'>
						<td><%= post.title %></td>
						<td><%= post.ranking %></td>
						<td><a class="show_link" href='/posts/<%= post.slug %>/'>view</a></td> 
					</tr></a>
				<% end %> 
				</tbody>
			</table>
		</div>
		<br /><br />
	</div>
</div>

app/views/posts/edit.html.erb
<% provide(:page_title, "Edit") %>


<h1>Edit Post</h1>

<%= render 'form', post: @post %>
<br />
<%= link_to 'Show', @post, class: 'white' %> |
<%= link_to 'Back', posts_path, class: 'white' %>

app/views/posts/index.html.erb
<% provide(:page_title, "Home") %>

<div class="row">
  <div class="col-xs-12">
   <br />
    <% @posts.each do |p| %>
      <% if p.ranking == "headline" %>
        <a href='/posts/<%= p.slug %>'>
        <div class="headline_div">
          <div class="headline_container">
            <%= image_tag p.photo, class: 'headline_img' %>
          </div>
          <h1 class="headline_title"><%= p.title %></h1>
          <h2 class="text-muted headline_sub"><%= p.description %></h2>
          <br><br>
        </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row"> 


 
    <% @posts.each do |post| %>
       <% if post.ranking == "today" %>
        <a class="cancel_link" href='/posts/<%= post.slug %>/'>
          <div class='col-sm-6 col-lg-4'>
            <div class="card">
              <div class="card-topper">
                <%= image_tag post.photo, class: 'card_image' %>
              </div>
              <div class="card-block">
               <h4 class="card-title"><%= post.title %></h4>
                <p class="published-date"><%= post.day_published %></p>
                <p class="card-text"><%= truncate(post.content, length: 150) %></p>
              </div>
            </div>
          </div>
        </a>
       <% end %>
    <% end %> 

</div>

app/views/posts/local_news.html.erb
<% provide(:page_title, "Local News") %>

<div class="row">
  <div class="col-xs-12">
  	<h1 class="section_header">Local News</h1>
	<hr  class="break" /><br />
    <% @posts.each do |p| %>
      <% if p.ranking == "headline local"%>
        <a href='/posts/<%= p.slug %>'>
        <div class="headline_div">
          <div class="headline_container">
            <%= image_tag p.photo, class: 'headline_img' %>
          </div>
          <h1 class="headline_title"><%= p.title %></h1>
          <h2 class="text-muted headline_sub"><%= p.description %></h2>
          <br><br>
        </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row"> 


 
    <% @posts.each do |post| %>
       <% if post.ranking == "local" %>
        <a class="cancel_link" href='/posts/<%= post.slug %>'>
          <div class='col-sm-6 col-lg-4'>
            <div class="card">
              <div class="card-topper">
                <%= image_tag post.photo, class: 'card_image' %>
              </div>
              <div class="card-block">
               <h4 class="card-title"><%= post.title %></h4>
                <p class="published-date"><%= post.day_published %></p>
                <p class="card-text"><%= truncate(post.content, length: 150) %></p>
              </div>
            </div>
          </div>
        </a>
       <% end %>
    <% end %> 
</div>

app/views/posts/new.html.erb
<% provide(:page_title, "New Post") %>
<div class="row">
  	<div class="col-xs-12 col-sm-8 col-sm-push-2">
		<h3>New Post</h3>
		<br />
		<%= render 'form', post: @post %>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>

<div class="row">
	<div class=" col-md-8 col-sm-12">
		<h1 class="heavy"><%= @post.title %></h1>
		<h4 class="text-muted"><%= @post.description %></h4>
		<p class="date"><%= @post.day_published %></p>

		<%= social_share_button_tag(@post.title, image: @post.photo) %>
		<br />
		<div>
			<%= image_tag @post.photo, class: 'banner' %>
		</div>
		<br />
		<p class="date"><%= @post.caption %></p>
		<br />
		<p><%= simple_format(@post.content) %></p>
		<br /><br />
		<% if user_signed_in? %>
		<%= link_to 'Edit', edit_post_path(@post), class: 'white' %> | <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: 'white' %> 
		<% end %> 
		<br />
		<br />
	</div>
	<div class="col-sm-0 col-md-4 sidebarouter">
		<div class="col-md-11 col-md-push-1 sidebar">
			<div class="sidebar_head_container">
				<h4 class="sidebar_header text-center">Other Stories</h4>
			</div>
		<% @posts.each do |p| %>
			<a href='/posts/<%= p.slug %>'>
				<% if p.ranking == "today" && p.title != @post.title %>
				<div class="photo_div">
					<%= image_tag p.photo, class: "photo_small" %>
					<h5 class="white_green"><%= p.title %></h5>
				</div>
				<% end %>
			</a>
		<% end %>
		</div>
		<div class="col-md-11 col-md-push-1 sidebar2">
			<div class="sidebar_head_container">
				<h4 class="sidebar_header text-center">Local News</h4>
			</div>
				<% @sidebar.each do |s| %> 
					<a href='/posts/<%= s.slug %>'>
						<% if s.title != @post.title %>
							<div class="photo_div">
								<%= image_tag s.photo, class: "photo_small" %>
								<h5 class="white_green"><%= s.title %></h5>
							</div>
						<% end %>
					</a>
				<% end %>
		</div>
	</div>
</div>

app/views/posts/sports.html.erb
<% provide(:page_title, "Sports") %>


<div class="row">
  <div class="col-xs-12">
  	<h1 class="section_header">Sports News</h1>
	<hr class="break" /><br />
    <% @posts.each do |p| %>
      <% if p.ranking == "headline sports"%>
        <a href='/posts/<%= p.slug %>'>
        <div class="headline_div">
          <div class="headline_container">
            <%= image_tag p.photo, class: 'headline_img' %>
          </div>
          <h1 class="headline_title"><%= p.title %></h1>
          <h2 class="text-muted headline_sub"><%= p.description %></h2>
          <br><br>
        </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row"> 


 
    <% @posts.each do |post| %>
       <% if post.ranking == "sports" %>
        <a class="cancel_link" href='/posts/<%= post.slug %>'>
          <div class='col-sm-6 col-lg-4'>
            <div class="card">
              <div class="card-topper">
                <%= image_tag post.photo, class: 'card_image' %>
              </div>
              <div class="card-block">
               <h4 class="card-title"><%= post.title %></h4>
                <p class="published-date"><%= post.day_published %></p>
                <p class="card-text"><%= truncate(post.content, length: 150) %></p>
              </div>
            </div>
          </div>
        </a>
       <% end %>
    <% end %> 
</div>